FROM ubuntu:bionic

LABEL Maintainer "Malcolm Jones <bossjones@theblacktonystark.com>"

ENV NON_ROOT_USER=developer \
    container=docker \
    TERM=xterm-256color

ARG HOST_USER_ID=1000
ENV HOST_USER_ID ${HOST_USER_ID}
ARG HOST_GROUP_ID=1000
ENV HOST_GROUP_ID ${HOST_GROUP_ID}


# Install packages for building ruby
RUN apt-get update && \
    apt-get install -y --force-yes build-essential curl git && \
    apt-get install -y --force-yes zlib1g-dev libssl-dev libreadline-dev libyaml-dev libxml2-dev libxslt-dev bash-completion vim && \
    apt-get clean

# # Install rbenv and ruby-build
# RUN git clone https://github.com/sstephenson/rbenv.git /root/.rbenv
# RUN git clone https://github.com/sstephenson/ruby-build.git /root/.rbenv/plugins/ruby-build
# RUN /root/.rbenv/plugins/ruby-build/install.sh
# ENV PATH /root/.rbenv/bin:$PATH
# RUN echo 'eval "$(rbenv init -)"' >> /etc/profile.d/rbenv.sh # or /etc/profile
# RUN echo 'eval "$(rbenv init -)"' >> .bashrc

# # Install multiple versions of ruby
# ENV CONFIGURE_OPTS --disable-install-doc
# ADD ./versions.txt /root/versions.txt
# RUN xargs -L 1 rbenv install < /root/versions.txt

# # Install Bundler for each version of ruby
# RUN echo 'gem: --no-rdoc --no-ri' >> /.gemrc
# RUN bash -l -c 'for v in $(cat /root/versions.txt); do rbenv global $v; gem install bundler; done'

# rbenv and ruby-build
RUN curl -fsSL "https://github.com/rbenv/rbenv/archive/v1.1.1.tar.gz" -o /opt/rbenv.tar.gz \
    && tar -C /opt/ -xzf /opt/rbenv.tar.gz \
    && rm /opt/rbenv.tar.gz && \
    curl -fsSL "https://github.com/rbenv/ruby-build/archive/v20180822.tar.gz" -o /opt/ruby-build.tar.gz \
    && tar -C /opt/rbenv/plugins/ -xzf /opt/ruby-build.tar.gz \
    && rm /opt/ruby-build.tar.gz
ADD rbenv.sh /etc/profile.d/rbenv.sh

# # install rubys
# RUN bash -c 'set -euo pipefail; \
#     . /etc/profile.d/rbenv.sh; \
#     curl -fsSL "https://github.com/rbenv/rbenv-each/archive/master.tar.gz" -o /opt/rbenv.tar.gz \
#     && tar -C /opt/ -xzf rbenv.tar.gz \
#     && rm rbenv.tar.gz && \


#     git clone https://github.com/znz/rbenv-plug /opt/rbenv/plugins/rbenv-plug; \
#     rbenv plug each; \
#     export CONFIGURE_OPTS="--disable-install-rdoc --disable-install-doc"; \
#     for v in \
#     2.4.2 \
#     ; do \
#     echo install $v; \
#     rbenv install $v; \
#     done \
#     '

RUN set -xe \
    && useradd -U -d /home/${NON_ROOT_USER} -m -r -G adm,tty,audio ${NON_ROOT_USER} \
    && usermod -a -G ${NON_ROOT_USER} -s /bin/bash -u ${HOST_USER_ID} ${NON_ROOT_USER} \
    && groupmod -g ${HOST_GROUP_ID} ${NON_ROOT_USER} \
    && ( mkdir /home/${NON_ROOT_USER}/.ssh \
    && chmod og-rwx /home/${NON_ROOT_USER}/.ssh \
    && echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key" > /home/${NON_ROOT_USER}/.ssh/authorized_keys \
    ) \
    && echo "${NON_ROOT_USER}     ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers \
    && echo "%${NON_ROOT_USER}     ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers \
    && cat /etc/sudoers \
    && echo "${NON_ROOT_USER}:${NON_ROOT_USER}" | chpasswd && \
    mkdir /var/run/dbus && \
    mkdir -p /home/${NON_ROOT_USER}/.local/bin && \
    chown ${NON_ROOT_USER}:${NON_ROOT_USER} -Rv /home/${NON_ROOT_USER}

USER ${NON_ROOT_USER}
WORKDIR /home/${NON_ROOT_USER}

ENV LANG C.UTF-8
ENV CI true


ENV PATH="~/.local/bin:${PATH}"

ENV PATH="/home/${NON_ROOT_USER}/.local/bin:${PATH}"
ENV PATH="/opt/scarlett-jhbuild/jhbuild/bin:${PATH}"
ENV PATH="/opt/jhbuild/bin:${PATH}"
# ENV PATH="/usr/lib/ccache:${PATH}"
